open-cluster-management-io/multicluster-controlplane

hack/start-multicluster-controlplane.sh
Signed-off-by: clyang82 <chuyang@redhat.com>
=> Set SERVING_IP

hack/demo/next-generation.sh, hack/deploy-multicluster-controlplane.sh, hack/deploy/controlplane/deployment.yaml, hack/deploy/controlplane/kustomization.yaml
couples of updates:
1. the `quay.io/open-cluster-management/multicluster-controlplane` is ready for using
2. update global hub to align with the changes of https://github.com/clyang82/multicluster-global-hub-lite/pull/7
=> Update demo scripts

.copyrightignore, .gitignore, hack/deploy-multicluster-controlplane.sh, hack/lib/init.sh, hack/lib/logging.sh, hack/lib/util.sh, hack/start-multicluster-controlplane.sh
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
=> fix deploy shell scripts

hack/deploy/controlplane/deployment.yaml, pkg/apiserver/options/options.go
Signed-off-by: morvencao <lcao@redhat.com>
=> add profiling flag and disable it in deploy manifest.

test/e2e/managed_cluster_test.go
Signed-off-by: myan <myan@redhat.com>
Reference: https://github.com/open-cluster-management-io/multicluster-controlplane/pull/14, https://github.com/open-cluster-management-io/multicluster-controlplane/issues/3
=> check managed cluster for each controlplane in the e2e test

.github/workflows/go-postsubmit.yaml, .github/workflows/go-presubmit.yaml, .github/workflows/go-release.yaml
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> upgrade github action

hack/deploy-multicluster-controlplane.sh, hack/deploy/controlplane/deployment.yaml, hack/deploy/controlplane/external-etcd-patch.yaml, hack/deploy/controlplane/kustomization.yaml, hack/deploy/controlplane/pvc.yaml
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> use pv with embed etcd deploy mode

hack/deploy-etcd.sh, hack/deploy-multicluster-controlplane.sh, hack/deploy/controlplane/external-etcd-patch.yaml, hack/deploy/etcd/statefulset.yaml
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> fix service name and etcd-prefix error

hack/deploy-etcd.sh, hack/deploy/etcd/kustomization.yaml, test/bin/setup-dep.sh, test/bin/setup-e2e.sh
Signed-off-by: myan <myan@redhat.com>
=> add external etcd for e2e test

.github/workflows/go-presubmit.yaml, test/bin/setup-e2e.sh
Signed-off-by: morvencao <lcao@redhat.com>
=> fix incorrect image in e2e testing.

hack/deploy/controlplane/deployment.yaml, hack/deploy/controlplane/external-etcd-patch.yaml, hack/start-multicluster-controlplane.sh, pkg/controllers/kubecontroller/controllermanager.go, pkg/controllers/kubecontroller/core.go, pkg/controllers/kubecontroller/options/options.go, pkg/controllers/kubecontroller/options/serviceaccountcontroller.go, pkg/servers/aggregator.go, pkg/servers/options/options.go, pkg/servers/server.go, test/bin/setup-integration.sh
Signed-off-by: morvencao <lcao@redhat.com>
=> add serviceaccount controller.

pkg/controllers/kubecontroller/clusterroleaggregation.go, pkg/controllers/kubecontroller/controllermanager.go, test/bin/setup-e2e.sh
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> add clusterrole aggregation controller

.github/workflows/go-postsubmit.yaml, .github/workflows/go-release.yaml
fixed: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/44
=> Upgrade imagebuilder

config/crds/bootstrap.go
PollUntil tries a condition func until it returns true, an error or stopCh is closed.
=> fix wrong usage for PollUntil

Makefile, README.md, go.mod, hack/deploy-multicluster-controlplane.sh, hack/deploy/controlplane/clusterrole-node.yaml, hack/deploy/controlplane/clusterrolebinding-admin.yaml, hack/deploy/controlplane/role-route.yaml, hack/deploy/controlplane/role.yaml, hack/deploy/controlplane/rolebinding-node.yaml, hack/deploy/controlplane/rolebinding-route.yaml, pkg/certificate/certificate.go, pkg/servers/configs/configs.go, pkg/servers/options/options.go, pkg/util/util.go, test/e2e/hack/e2e.sh
related issue: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/41
=> enable deploy to eks and kind cluster

hack/start-multicluster-controlplane.sh, pkg/agent/agent.go, pkg/controllers/ocmcontroller/ocmcontroller.go, pkg/util/recorder.go, test/performance/cluster/create.go
1. increase work controller worker numbers
2. introduce a logging record only to print the log info
=> increase work controller worker numbers

test/integration/hack/integration.sh
fix: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/66
=> fix integration test error

.github/workflows/go-release.yaml
https://github.com/open-cluster-management-io/multicluster-controlplane/actions/runs/5205641682/jobs/9395653600#step:5:48
=> fix release chart bug

.github/workflows/go-release.yaml
refer to this https://github.com/open-cluster-management-io/cluster-proxy/pull/163
=> remove debug when release chart

README.md
For `https://github.com/open-cluster-management-io/ocm/issues/126#issuecomment-1610266458`
=> Add a rough description of what this project is

charts/multicluster-controlplane/values.yaml, hack/deploy-multicluster-controlplane.sh
ref: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/98
=> Disable route by default

charts/multicluster-controlplane/templates/_validate.tpl, charts/multicluster-controlplane/values.yaml
This field is not used anywhere except for the validation check. So, I am removing it.
=> Remove baseDomain in chart

hack/start-multicluster-controlplane.sh
related issue: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/81
=> restrict data directory permission

pkg/servers/options/options.go
fixed: https://github.com/open-cluster-management-io/multicluster-controlplane/issues/131
=> Skip health endpoints in etcdoptions

pkg/controllers/ocmcontroller/ocmagent.go
The multicluster-controlplane pod terminates with the message: `the server could not find the requested resource (post managedclusters.cluster.open-cluster-management.io)`
=> Wait until managedCluster resource to be created.

OWNERS
Signed-off-by: myan <myan@redhat.com>
=> Add yanmxa to OWNER
